// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6J5s3mmB4U2yHpY39pTzgJ0Wb8ftcB0',
    appId: '1:945546833003:web:1c46877e4a9637fc9c552e',
    messagingSenderId: '945546833003',
    projectId: 'cima-38025',
    authDomain: 'cima-38025.firebaseapp.com',
    storageBucket: 'cima-38025.firebasestorage.app',
    measurementId: 'G-TBYNJ6VP6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa63qbWT0zw8nC7YRrGmelQsu9GJH8WXM',
    appId: '1:945546833003:android:351565ac3ae7123f9c552e',
    messagingSenderId: '945546833003',
    projectId: 'cima-38025',
    storageBucket: 'cima-38025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSt78lGscbpx0enuYx1UZSvf_puX_DViI',
    appId: '1:945546833003:ios:7ed9f730e7f94dad9c552e',
    messagingSenderId: '945546833003',
    projectId: 'cima-38025',
    storageBucket: 'cima-38025.firebasestorage.app',
    iosBundleId: 'com.example.onlineinspection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSt78lGscbpx0enuYx1UZSvf_puX_DViI',
    appId: '1:945546833003:ios:7ed9f730e7f94dad9c552e',
    messagingSenderId: '945546833003',
    projectId: 'cima-38025',
    storageBucket: 'cima-38025.firebasestorage.app',
    iosBundleId: 'com.example.onlineinspection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg6J5s3mmB4U2yHpY39pTzgJ0Wb8ftcB0',
    appId: '1:945546833003:web:40729a1e028bb8f79c552e',
    messagingSenderId: '945546833003',
    projectId: 'cima-38025',
    authDomain: 'cima-38025.firebaseapp.com',
    storageBucket: 'cima-38025.firebasestorage.app',
    measurementId: 'G-L6DBM0PCZB',
  );
}
